name: Mikero Packer
description: Uses Mikero Tools to pack PBOs
runs:
  using: composite
  steps:
    - name: Install Mikero Tools for packing
      run: | 
        $obfusctedAddons = @("braf_teste")
        $nonObfuscatedAddons = @("braf_outro_teste")
        $mainDirectory = Split-Path -parent $MyInvocation.MyCommand.Definition
        # Env variables from the action.yml file
        $outputDirectory = "$env:OUTPUT_DIRECTORY"
        $keyDirectory = "$env:KEY_DIRECTORY"
        $excludeFromAddonString = "$env:EXCLUDE_FROM_PBO"
        $exclusionModifierString = "$env:EXCLUSION_MODIFIER"

        foreach ($addon in $nonObfuscatedAddons) {
                # Pack the addon
                $addonDirectory = (Resolve-Path $addon).Path
                Write-Output "Packing $addon"
                Write-Output $addonDirectory
                Write-Output "pboProject.exe -P +N +K=$keyDirectory +C -Z=$exclusionModifierString -B -X=$excludeFromAddonString $addonDirectory +M=$outputDirectory"
        }
        foreach ($addon in $obfusctedAddons) {
                # Pack the addon
                Write-Output "Packing $rootFolder"
                pboProject.exe +N +K=$keyDirectory +C -Z=$exclusionModifierString -B -X=$excludeFromAddonString +O $mainDirectory"\"$addon +M=$outputDirectory > NUL  
        }
      shell: pwsh