name: Mikero Packer
description: Uses Mikero Tools to pack PBOs
runs:
  using: composite
  steps:
    - name: Install Mikero Tools
      run: | 
        # This script is used to get the root folders of the files changed in the last commit, each root folders into the BRAF project is a different addon that must packed into an PBO
        # Author: Valmo Trindade
        $obfusctedAddons = @("braf_teste")
        $nonObfuscatedAddons = @("braf_outro_teste")
        $mainDirectory = Split-Path -parent $MyInvocation.MyCommand.Definition
        # Env variables from the action.yml file
        echo +$env:OUTPUT_DIRECTORY
        # $outputDirectory = $mainDirectory+$env:OUTPUT_DIRECTORY
        # $keyDirectory = $mainDirectory+$env:KEY_DIRECTORY
        $excludeFromAddonString = $env:EXCLUDE_FROM_PBO
        $exclusionModifierString = $env:EXCLUSION_MODIFIER
        if (-not $env:EXCLUDE_FROM_PBO) {
            $env:EXCLUDE_FROM_PBO = "*.h,*.hpp,*.png,*.cpp,*.txt,thumbs.db,*.dep,*.bak,*.log,*.pew,source,*.tga,*.bat,*.psd,*.cmd,*.mcr,*.fbx,*.max"
        }
        if (-not $env:EXCLUSION_MODIFIER) {
            $env:EXCLUSION_MODIFIER = "init*.sqf,init*.sqs"
        }
        if (Test-Path -Path $outputDirectory) {
            Write-Output "Folder $outputDirectory already exists"
        } else {
            Write-Output "Creating build folder"
            mkdir $outputDirectory
        }
        foreach ($addon in $nonObfuscatedAddons) {
                # Pack the addon
                Write-Output "Packing $rootFolder"
                pboProject.exe +N +K=$keyDirectory +C -Z=$exclusionModifierString -B -X=$excludeFromAddonString $mainDirectory"\"$addon +M=$outputDirectory
        }
        foreach ($addon in $obfuscatedAddons) {
                # Pack the addon
                Write-Output "Packing $rootFolder"
                pboProject.exe +N +K=$keyDirectory +C -Z=$exclusionModifierString -B -X=$excludeFromAddonString +O $mainDirectory"\"$addon +M=$outputDirectory
        }
      shell: pwsh